Repository faccts/opi, pull requests merged in 2025-09, with the labels that each got.

#117 Add simple property function to structure for counting the number of electrons
  examples/exmp044_from_ase/job.py
  src/opi/input/structures/structure.py
Labels: enhancement, side input

#122 Fixed `opi.__version__`
  src/opi/__init__.py
Labels: bug

#125 Docu: "--no-advice" would crash with older git versions.
  docs/conf.py
  src/opi/utils/orca_version.py
Labels: bug, documentation

#126 NOX: Exiting with non-zero status if ruff altered the source code
  noxfile.py
Labels: enhancement

#128 Minimal CI workflow for executing uv run nox upon a PR to main
  .github/workflows/pr_checks.yml
Labels: enhancement

#136 pr_checks.yml: Small improvements.
  .github/workflows/pr_checks.yml
  noxfile.py
Labels: enhancement

#138 Parsing of multiple xyz files in Structure
  examples/README.md
  examples/exmp045_existing_calc/job.py
  examples/exmp047_trj/inp_trj.xyz
  examples/exmp047_trj/job.py
  examples/exmp047_trj/with_blank_lines_trj.xyz
  examples/exmp047_trj/with_comments_trj.xyz
  src/opi/input/structures/structure.py
  src/opi/utils/textio.py
  tests/examples/test_exmp047_trj.py
Labels: bug, enhancement, side input

#147 Allow variable suffixes for gbw json files
  examples/README.md
  examples/exmp048_loc_gbw/inp.xyz
  examples/exmp048_loc_gbw/job.py
  src/opi/execution/core.py
  src/opi/output/core.py
  tests/examples/test_exmp048_loc_gbw.py
Labels: enhancement, side output
